CleverLabs/stagy

.env, Gemfile, Gemfile.lock, app/services/git_wrapper.rb, app/services/server_access/heroku.rb, app/services/server_access/heroku_database.rb, config/environments/production.rb
=> Add heroku api key, fix pushing non-master branches

app/controllers/project_instances_controller.rb, app/jobs/server_actions_call_job.rb, app/services/deployment/processes/create_project_instance.rb, app/services/deployment/server_actions/create.rb, app/views/project_instances/show.html.slim
set an instance status and application_url
=> [#46] Update project instance within worker

app/constants/deployment_configuration_constants.rb, app/controllers/application_controller.rb, app/controllers/deployment_configuration_statuses_controller.rb, app/controllers/deployment_configurations_controller.rb, app/controllers/project_instances_controller.rb, app/controllers/project_user_roles_controller.rb, app/controllers/projects_controller.rb, app/helpers/project_helper.rb, app/helpers/project_instance_helper.rb, app/services/deployment/configuration_builder.rb, app/services/github/router.rb, app/services/github/webhook_processors/add_new_repo.rb, app/views/deployment_configurations/edit.html.slim, app/views/project_instances/index.html.slim, app/views/project_instances/new.html.slim, app/views/project_instances/show.html.slim, app/views/projects/index.html.slim, app/views/projects/show.html.slim, config/routes.rb
Add ability to enter branch on project manual project instance creation
Add ability to change deployment configuration statuses
=> [#70][#64] Add ability to add new user

app/constants/github/pull_request_constants.rb, app/jobs/server_actions_call_job.rb, app/jobs/webhook_resolver_job.rb, app/services/deployment/action_flow_controller.rb, app/services/deployment/configuration.rb, app/services/deployment/processes/create_attached_project_instance.rb, app/services/deployment/project_instance_events.rb, app/services/deployment/repositories/project_instance_repository.rb, app/services/github/events/pull_request.rb, app/services/github/pull_request.rb, app/services/github/webhook_processors/add_new_repo.rb, app/services/github/webhook_processors/close_pull_request.rb, app/services/github/webhook_processors/create_project.rb, app/services/github/webhook_processors/create_pull_request.rb, app/services/github/webhook_processors/delete_project.rb, app/services/github/webhook_processors/remove_repo.rb, app/services/github/webhook_processors/update_pull_request.rb, app/services/notifications/comment.rb, db/migrate/20190627093439_add_repo_path_to_project_instances.rb, db/schema.rb
=> [#29] Add status messages to github pull request

app/constants/project_instance_constants.rb, app/javascript/packs/homeChart.ts, app/services/deployment/processes/destroy_project_instance.rb, app/services/deployment/processes/update_project_instance.rb, app/services/git_wrapper.rb
Improve branch checkout process - we need to reset to not resolve conflicts
=> Don't launch destroy process if instance is not deployed

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/projects_controller.rb, app/services/github/router.rb, app/views/project_instances/show.html.slim, app/views/projects/index.html.slim, db/fixtures/01_addons.rb, db/migrate/20190715114641_add_constraints_to_name_at_addons.rb, db/schema.rb, db/seeds.rb
Add count of deployment configurations
Add addons seeds
=> Add link to pull requests in project instances

.env, app/controllers/project_instances/deploys_controller.rb, app/services/server_access/heroku.rb, app/services/server_access/heroku_helpers/level.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/18/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/18/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/18)
=> Add dyno and db level handling

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/jobs/application_job.rb, app/models/addon.rb, app/models/build_action.rb, app/models/deployment_configuration.rb, app/models/deployment_configurations_addon.rb, app/models/project.rb, app/models/project_instance.rb, app/models/project_user_role.rb, app/models/slack_entity.rb, app/models/user.rb, app/models/web_process.rb, db/migrate/20190731143752_create_versions.rb, db/migrate/20190731143753_add_object_changes_to_versions.rb, db/schema.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/20/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/20/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/20)
=> [#95] Add paper trail

app/services/deployment/helpers/addons_builder.rb, app/services/deployment/server_actions/create.rb, app/services/deployment/server_actions/recreate.rb, app/services/deployment/server_actions/rollback.rb, config/locales/build_actions/log.en.yml
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/26/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/26/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/26)
=> [#119] Separate states for each addon provider

Gemfile, Gemfile.lock, app/constants/omniauth_constants.rb, app/controllers/sessions_controller.rb, app/models/auth_info.rb, app/models/user.rb, app/services/github/user.rb, app/services/github/webhook_processors/revoke_auth.rb, app/services/gitlab/user.rb, app/services/omniauth/auth_info_presenter.rb, app/services/omniauth/user_factory.rb, app/views/sessions/show.html.slim, config/initializers/omniauth.rb, db/migrate/20190814074832_create_auth_info.rb, db/migrate/20190814121526_move_users_github_entitiy_to_auth_info.rb, db/schema.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/29/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/29/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/29)
=> [#124] Add gitlab user, allow sign in from gitlab

app/controllers/slack/authentications_controller.rb, config/routes.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/30/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/30/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/30)
=> [#110] Redirect to project config page when slack notification cancelled

db/migrate/20190823082651_move_deployment_configurations_to_repositories.rb, db/migrate/20190826122633_move_deployment_configurations_addons_to_repositories_addons.rb, db/migrate/20190826162712_drop_deployment_configurations.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/35/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/35/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/35)
=> [#139] Update renaming  migrations

app/constants/repository_constants.rb, app/controllers/gitlab_integration/repositories_controller.rb, app/controllers/repositories_controller.rb, app/models/repository.rb, app/services/repository_form.rb, app/views/gitlab_integration/repositories/new.html.slim, app/views/repositories/new.html.slim, db/migrate/20191011085824_add_container_to_repositories.rb, db/schema.rb
resolves #166 
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/52/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/52/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/52)
=> [#166] Containerization in repository. UI

app/services/git_providers/url/new_repository.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/59/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/59/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/59)
=> [#175] Initialize github router

app/services/server_access/heroku_helpers/level.rb, db/fixtures/01_addons.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/63/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/63/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/63)
=> Add ClearDB

app/services/gitlab_integration/project_creator.rb
resolves #178
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/80/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/80/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/80)
=> [#178] Use only repositories from selected namespace

app/services/github/webhooks/processors/update_pull_request.rb, app/services/omniauth/auth_info_presenter.rb
Fix bug of updating non-deployed instance
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/87/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/87/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/87)
=> [#188] Use nickname if there is no full name

app/constants/project_instance_constants.rb, app/controllers/project_instances_controller.rb, app/services/deployment/processes/destroy_project_instance.rb
Status name: 'CLOSED_NEVER_CREATED'
Resolves #183 
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/104/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/104/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/104)
=> [#183] Add new project instance deployment status

app/controllers/slack/authentications_controller.rb
Fixes #193 
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/107/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/107/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/107)
=> [#193] Use correct oauth data from slack

app/constants/repository_constants.rb, app/controllers/gitlab_integration/repositories_controller.rb, app/controllers/projects_controller.rb, app/controllers/repositories_controller.rb, app/helpers/application_helper.rb, app/models/json_models/project_instance_configuration.rb, app/models/project_instance.rb, app/models/repository.rb, app/services/deployment/build_configuration.rb, app/services/deployment/configuration.rb, app/services/deployment/configuration_builders/by_project.rb, app/services/deployment/configuration_builders/by_project_instance.rb, app/services/deployment/helpers/push_code_to_server.rb, app/services/deployment/server_actions/create.rb, app/services/repository_form.rb, app/services/server_access/heroku_helpers/docker_deploy_config_generator.rb, app/views/gitlab_integration/repositories/new.html.slim, app/views/project_instances/build_actions/show.html.slim, app/views/projects/show.html.slim, app/views/repositories/edit.html.slim, app/views/repositories/new.html.slim, db/migrate/20191022113650_rename_container_to_build_type_on_repositories.rb, db/schema.rb, lib/provider_api/github/app_client.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/109/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/109/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/109)
=> Private gems

app/controllers/gitlab_integration/repositories_controller.rb, app/controllers/repositories_controller.rb, app/services/deployment/build_configuration.rb, app/services/deployment/configuration_builders/by_project.rb, app/services/deployment/configuration_builders/env_variables_builder.rb, app/services/deployment/helpers/push_code_to_server.rb, app/services/repository_form.rb, app/services/server_access/heroku_helpers/docker_deploy_config_generator.rb, app/views/gitlab_integration/repositories/new.html.slim, app/views/repositories/edit.html.slim, app/views/repositories/new.html.slim, db/migrate/20191022144738_add_build_env_variables_to_repositories.rb, db/schema.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/131/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/131/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/131)
=> [#201] Add ENV variables for docker build stage

app/controllers/gitlab_integration/projects_controller.rb, app/pages/gitlab_integration/project_page.rb
resolves #154 
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/132/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/132/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/132)
=> [#154] Do not show created gitlab project names

app/controllers/repositories_controller.rb, app/services/deployment/configuration.rb, app/services/deployment/configuration_builders/by_project.rb, app/services/deployment/configuration_builders/by_project_instance.rb, app/services/deployment/server_actions/create.rb, app/services/repository_form.rb, app/services/server_access/heroku.rb, app/views/gitlab_integration/repositories/new.html.slim, app/views/repositories/edit.html.slim, config/locales/build_actions/log.en.yml, db/migrate/20191025133552_add_buildpacks_to_repositories.rb, db/schema.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/173/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/173/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/173)
=> [#13] Add primitive buildpacks management

app/services/notifications/comment.rb, app/services/server_access/heroku_helpers/level.rb
---
[Create QA instance](https://deployqa.dev/projects/2/project_instances/181/deploy)
[Create custom QA instance](https://deployqa.dev/projects/2/project_instances/181/deploy?custom_deploy=true)
[Configuration](https://deployqa.dev/projects/2/project_instances/181)
=> Reduce heroku instance level. Add new PR icons

app/controllers/gitlab_integration/repositories_controller.rb, app/controllers/repositories_controller.rb, app/services/deployment/configuration.rb, app/services/deployment/configuration_builders/by_project.rb, app/services/deployment/configuration_builders/by_project_instance.rb, app/services/deployment/server_actions/create.rb, app/services/repository_form.rb, app/services/server_access/heroku.rb, app/views/gitlab_integration/repositories/new.html.slim, app/views/repositories/edit.html.slim, config/environments/production.rb, config/locales/build_actions/log.en.yml, db/migrate/20191029143557_add_migration_command_to_repositories.rb, db/schema.rb, lib/action_state_machine.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/193/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/193/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/193)
=> [#208] Implement seeds command

app/controllers/project_instances/addons_controller.rb, app/services/deployment/action_flow_controller.rb, app/services/deployment/addon.rb, app/services/deployment/helpers/addons_credentials_parser.rb, app/services/deployment/server_actions/create.rb, app/services/server_access/heroku.rb, app/views/project_instances/addons/index.html.slim, app/views/project_instances/show.html.slim, config/locales/build_actions/log.en.yml, config/routes.rb, db/fixtures/01_addons.rb, db/migrate/20191025151329_add_credentials_names_to_addons.rb, db/migrate/20191030155523_fill_addons_credentials_envs.rb, db/schema.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/204/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/204/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/204)
=> [#189] Addons credentials

app/constants/project_user_role_constants.rb, app/controllers/project_user_roles_controller.rb, app/views/projects/show.html.slim
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/216/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/216/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/216)
=> [#184] Remove users list from repo config

app/services/server_access/heroku.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/220/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/220/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/220)
=> [#217] Retry heroku several times

app/services/deployment/action_flow_controller.rb, app/views/project_instances/addons/index.html.slim, config/locales/build_actions/log.en.yml
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/230/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/230/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/230)
=> Add deployment time

config/routes.rb, lib/routes/logged_user_constraint.rb
Fixes #158 
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/227/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/227/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/227)
=> [#158] Fix typo error in LoggedUserConstraint

app/controllers/project_instances/configurations_controller.rb, app/services/deployment/helpers/env_aliasing.rb, app/services/deployment/server_actions/create.rb, app/services/notifications/comment.rb, app/services/repository_form.rb, app/views/gitlab_integration/repositories/new.html.slim, app/views/project_instances/configurations/edit.html.slim, app/views/repositories/edit.html.slim, app/views/repositories/new.html.slim, config/initializers/rollbar.rb
Add git reference to rollbar and filter 'not found' exceptions
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/246/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/246/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/246)
=> [#230] Add ability to alias ENV variables

.travis.yml, app/services/github/user.rb, lib/provider_api/github/user_client.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/470/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/470/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/470)
=> Fetch github email

app/controllers/project_instances/configurations_controller.rb, app/policies/project_instance_policy.rb, app/services/deployment/processes/update_project_instance_configuration.rb, app/views/project_instances/configurations/edit.html.slim, app/views/project_instances/show.html.slim, config/locales/views/project_instances.en.yml
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/491/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/491/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/491)
=> [240] Allow to edit ENV variables after failed deploy

app/controllers/sessions_controller.rb, app/services/auth/github/setup_user_projects_membership.rb, app/services/auth/gitlab/setup_user_projects_membership.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/510/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/510/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/510)
=> Rename AddUserToProjects constants

app/controllers/project_instances_controller.rb, app/policies/project_policy.rb, app/views/project_instances/index.html.slim
Resolves #238 
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/547/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/547/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/547)
=> [#238] Do not allow instance creation if there is no active repositories

app/services/deployment/helpers/refresh_project_instance_configuration.rb, app/services/deployment/processes/deploy_new_instance.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/572/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/572/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/572)
=> [#241] Refresh env variables of project instance before first deploy

app/models/email_whitelist.rb, app/services/auth/user_creator.rb, db/migrate/20200120082826_create_email_whitelist.rb, db/schema.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/661/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/661/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/661)
=> Create email whitelist

app/controllers/gitlab_integration/repositories_controller.rb, app/controllers/repositories_controller.rb, app/services/deployment/configuration.rb, app/services/deployment/configuration_builders/by_project.rb, app/services/deployment/configuration_builders/by_project_instance.rb, app/services/deployment/server_actions/create.rb, app/services/repository_form.rb, app/views/gitlab_integration/repositories/new.html.slim, app/views/repositories/edit.html.slim, db/migrate/20200120094447_rename_migrations_to_seeds.rb, db/schema.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/664/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/664/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/664)
=> [#221] Rename migrations command to seeds command

app/constants/addon_constants.rb, app/controllers/project_instances/configurations_controller.rb, app/controllers/project_user_roles_controller.rb, app/models/addon.rb, app/services/deployment/configuration.rb, app/services/deployment/helpers/env_aliasing.rb, app/services/deployment/server_actions/create.rb, db/migrate/20200204085607_add_addon_type_to_addons.rb, db/schema.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/755/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/755/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/755)
=> Add heroku ENV aliasing. Fix db creation for instances without db

app/services/aws_integration/s3_accessor.rb, app/services/aws_integration/user.rb, app/services/deployment/configuration_builders/by_project.rb, app/services/deployment/configuration_builders/env_variables_builder.rb, app/services/deployment/configuration_builders/name_builder.rb, app/services/deployment/helpers/refresh_project_instance_configuration.rb, app/services/plugins/adapters/new_project.rb, app/services/plugins/entry/on_project_creation.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/810/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/810/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/810)
=> Refactor external names

app/controllers/repositories_controller.rb, app/services/deployment/configuration.rb, app/services/deployment/configuration_builders/addons_builder.rb, app/services/deployment/configuration_builders/by_project.rb, app/services/deployment/configuration_builders/by_project_instance.rb, app/services/deployment/configuration_builders/env_variables_builder.rb, app/services/deployment/configuration_builders/helpers/exposures_builder.rb, app/services/deployment/configuration_builders/name_builder.rb, app/services/deployment/web_process.rb, app/services/repository_form.rb, app/views/project_instances/show.html.slim, app/views/repositories/edit.html.slim, db/fixtures/01_addons.rb, db/migrate/20200429120156_add_dockerfile_to_web_processes.rb, db/migrate/20200429153810_add_migration_command_and_schema_load_command_to_repositories.rb, db/migrate/20200429155240_add_expose_port_to_web_processes.rb, db/migrate/20200504132803_fill_expose_port_in_web_processes.rb, db/migrate/20200505122900_add_generate_domain_to_web_processes.rb, db/schema.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/1341/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/1341/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/1341)
=> Add ability to have multiple dockerfiles in one repo

Gemfile, Gemfile.lock, app/constants/cache_constants.rb, app/services/deployment/configuration_builders/addons_builder.rb, app/services/deployment/configuration_builders/helpers/exposures_builder.rb, app/services/deployment/configuration_builders/name_builder.rb, app/services/deployment/server_actions/destroy.rb, app/services/deployment/server_actions/rollback.rb, app/services/plugins/adapters/instance_destruction.rb, app/services/plugins/entry/on_instance_destruction.rb, app/services/robad/events/handler.rb, app/services/robad/resource_management/port.rb, config/initializers/redis.rb, lib/redis_storage.rb
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/1409/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/1409/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/1409)
=> Improve Ports Allocation service

app/controllers/gitlab_integration/repositories_controller.rb, app/pages/gitlab_integration/repository_page.rb, app/views/gitlab_integration/repositories/new.html.slim
---
[<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run.png' align='absmiddle' title='Deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/1610/deploy) [<img height="70" width="70" src='https://deployqa-production.s3.amazonaws.com/public-icons/run_with_setup_dark.png' align='absmiddle' title='Customize and deploy branch via DeployQA' />](https://deployqa.dev/projects/2/project_instances/1610/deploy?custom_deploy=true) [<img height="70" width="50" src='https://deployqa-production.s3.amazonaws.com/public-icons/setup.png' align='absmiddle' title='Open instance page' />](https://deployqa.dev/projects/2/project_instances/1610)
=> Gitlab. New Gitlab repos available for choosing on Repo Configuration Page
